Adding counters
mradamfrancis/teabot pull request #21
Opened 2017-02-21 23:21 UTC by davepmarshall

2017-02-21 23:22 UTC, davepmarshall commented on server.js
> +          client.incr('makecount-' + channel + '-' + teaMakerId)
Should this be teaMakerId or teaMaker ?

2017-02-21 23:22 UTC, davepmarshall commented on server.js
> +          client.incr('makecount-' + channel + '-' + teaMakerId)
Should this be teaMakerId or teaMaker ?

2017-02-21 23:24 UTC, davepmarshall commented
General comment, not sure if the redis incr command requires ```function(err, reply) ``` to work

2017-02-22 21:59 UTC, mradamfrancis requested changes
maybe we should do:
`client.incr('key1', function(err, reply) {
        console.log(reply); 
    });`
so that we check logs that it is incrementing correctly?

2017-02-22 21:59 UTC, mradamfrancis commented on server.js
> +          client.incr('makecount-' + channel + '-' + teaMakerId)
teaMakerId, so that we're consistent with drinkcount, startcount

2017-02-23 09:48 UTC, davepmarshall commented on server.js
> +          client.incr('makecount-' + channel + '-' + teaMakerId)
Cool

2017-02-23 09:59 UTC, davepmarshall commented
Shall we ship it and see what happens?

2017-02-23 10:06 UTC, merged